version: "3.8"
services: 
  web: 
    build: ./web/.
    ports:
      - "3000:3000"
    depends_on: 
      - api
    volumes:
      - ./web/.:/home/app/.
  api:
    build: ./api/.
    depends_on: 
      - database
    ports:
      - "5000:80"
  database: 
    image: postgres
    environment:
      - POSTGRES_DB=todoapp
      - POSTGRES_PASSWORD=123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
